name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: pedrohpsantos
          config_timezone: America/Sao_Paulo
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata  # базовый контент (информация о пользователе)
          plugin_introduction: yes 
          
          plugin_isocalendar: yes  # 3д изокалендарь
          plugin_isocalendar_duration: full-year  # отображает активность за полный год

          plugin_languages: yes  # отображение применяемых языков программирования
          plugin_languages_details: percentage  # дополнительная информация о коде размер и процент

          plugin_achievements: no
          plugin_achievements_threshold: X  # (покажет фишки достижений которые еще не разблокированы)
          plugin_achievements_display: detailed  # детальное описание фишек достижений

          plugin_calendar: yes  # отображает активность по годам от текущего и далее
          plugin_calendar_limit: 2 # отображает активность за столько лет

          plugin_topics: no  # плагин ипсользуемых тем
          plugin_topics_limit: 0
          plugin_topics_mode: icons
