name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: pedrohpsantos
          
          # === Visual Clean ===
          base: "" 
          config_timezone: America/Sao_Paulo
          config_style_css: |
             .stat { color: #cdd6f4; }
             .field { color: #cdd6f4; }
             .content { color: #cdd6f4; }
          
          # === Plugin: Linguagens ===
          plugin_languages: yes
          # Mostra tudo, exceto arquivos de configuração puros
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          
          plugin_languages_limit: 15
          plugin_languages_threshold: 0%
          
          # === A MÁGICA ESTÁ AQUI (Cores Manuais do Catppuccin) ===
          # Mapeando cada linguagem para uma cor da sua paleta preferida
          plugin_languages_colors: >-
            c:#89b4fa,
            python:#f9e2af,
            javascript:#a6e3a1,
            tsx:#cba6f7,
            vim script:#fab387,
            shell:#94e2d5,
            typescript:#f5c2e7,
            java:#f38ba8
          
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
